version: "3.8"
services:
  ###########################
  # Symfony apache project container
  ###########################
  www:
    build: ./
    container_name: ${PROJECT_NAME}_www
    ports:
      - ${PHP_APACHE_HOST_PORT}:80
    volumes:
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${BACKEND_DIR}:/var/www/html
    restart: always
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    networks:
      - php_unit_kata_network

networks:
  php_unit_kata_network:
